### ISSUE TITLE
Discreate layers Client Design Review 

### ISSUE THREAD

**Issue by asafMasa** [MapColonies/discrete-layer-client#13]
- Motivation: Describe the relevant product requirements or technical problem that you are addressing.
- Solution context: A diagram that shows the relevant component(s) within the context of the larger system.
- Solution overview: Describe the suggested solution in few sentences.
- Assumptions: Any assumptions that were taken prior to designing this solution.
- Solution diagram: Show the main building blocks of the solution.
- Technologies: List the underlying technologies being used, protocols, algorithms, 3rd party frameworks and libraries, databases, etc.
- Data model: if relevant, describe the data model, preferably in a diagram
- Flows: Describe the main use cases / user stories using UML interaction (sequence) diagrams. Include users and external systems/applications if relevant.
- Interfaces:
  - For front-end services: show the UX
  - For back-end services: list the API methods, messages or other protocols
- Error handling: Describe the main error cases and how you handle them or recover
- Security: Discuss security aspects, if relevant
- Performance and scalability: What is the expected performance of the solution? How is it optimized? How does it scale?
- Known limitations and open issues, if any

**Comment by alebinson** [comment]
[Discrete Layers Client design.pptx](https://github.com/MapColonies/discrete-layer-client/files/5415813/Discrete.Layers.Client.design.pptx)

**Comment by asafMasa** [comment]
https://github.com/MapColonies/discrete-layer-client/issues/8 - related to
