### ISSUE TITLE
UI/UX discrete layers

### ISSUE THREAD

**Issue by alebinson** [MapColonies/discrete-layer-client#8]
**Initial app state**
Buttons more tabs
![Initial_tab_view](https://user-images.githubusercontent.com/23166717/96114679-9c2afb80-0eee-11eb-8238-94a1cc15579d.png)

**Area of Interest (AOI)**
AOI opened state
![aoi_tab_opened](https://user-images.githubusercontent.com/23166717/96115170-35f2a880-0eef-11eb-85a2-f25ab81fe9dc.png)

**Filters**
Filters opened state look and feel
![filters_tab_opened](https://user-images.githubusercontent.com/23166717/96115289-62a6c000-0eef-11eb-8ab4-b068edeadb9d.png)

Filters with possible options due to collected metadata
As mentioned here https://github.com/MapColonies/GEEDocker/issues/12
![filters_tab_opened_with_possible_search_criteria_due_to_metadata](https://user-images.githubusercontent.com/23166717/96115468-a8fc1f00-0eef-11eb-9516-80007dc3d947.png)

**Results table**
After defining AOI
![results_table_after_selecting_AOI_with_opener](https://user-images.githubusercontent.com/23166717/96115669-fd9f9a00-0eef-11eb-8058-2986c6307d92.png)
When row selected in result table shown/highlighted appropriate layer on map(see purple boundaries)
When + expanded, more detailed layer data presented(according to collected metadata)

Result table in collapsed state
![results_table_after_drawing_AOI_collapsed_state](https://user-images.githubusercontent.com/23166717/96116604-650a1980-0ef1-11eb-9a66-c3385f6a9e1c.png)

Available actions on result state when it opened
![results_table_actions](https://user-images.githubusercontent.com/23166717/96116665-81a65180-0ef1-11eb-96cd-d684b0fbc84d.png)

**Comment by ssharon-rnd** [comment]
@alebinson Looks good
@shaziri @seganom are there any comments?
